export const GET_VIDEO_INFORMATION_REQUESTED = 'GET_VIDEO_INFORMATION_REQUESTED';
export const GET_VIDEO_INFORMATION_SUCCESS = 'GET_VIDEO_INFORMATION_SUCCESS';
export const GET_VIDEO_INFORMATION_ERROR = 'GET_VIDEO_INFORMATION_ERROR';
